Fix for invalid call from hook after uninstall

diff --git a/bin/jammer b/bin/jammer
--- a/bin/jammer
+++ b/bin/jammer
@@ -37,16 +37,23 @@ def install_git_hook
      puts "Overwriting existing hook..."
   end
 
-
   hook_content = <<~SCRIPT
   #!/bin/sh
   # Hook installed by jammer-cli
 
-  # Run the jammer keyword check
-  jammer
+  output=$(jammer 2>&1)
+  jammer_exit_code=$?
 
-  # Exit with the status from jammer (non-zero aborts commit)
-  exit $?
+
+  if [ $jammer_exit_code -eq 127 ]; then
+    echo "Warning: jammer command not found, skipping pre-commit check."
+    exit 0
+  elif [ $jammer_exit_code -ne 0 ]; then
+    echo "$output"
+    exit $jammer_exit_code
+  else
+    exit 0
+  fi
   SCRIPT
 
   begin
