Extract hook shell command to separate file

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,12 +1,15 @@
 #!/bin/sh
+# Hook installed by jammer-cli
 
-# Pre-commit hook to check for keywords using jammer-cli
+output=$(jammer 2>&1)
+jammer_exit_code=$?
 
-# Get the project root directory
-PROJECT_ROOT=$(git rev-parse --show-toplevel)
-
-# Run the jammer script before committing
-ruby "$PROJECT_ROOT/bin/jammer"
-
-# Exit with the status code from the jammer script
-exit $? 
+if [ $jammer_exit_code -eq 127 ]; then
+  echo "Warning: 'jammer' command not found, skipping pre-commit check."
+  exit 0
+elif [ $jammer_exit_code -ne 0 ]; then
+  echo "$output"
+  exit $jammer_exit_code
+else
+  exit 0
+fi
